# Device: https://www.waveshare.com/wiki/ESP32-S3-ETH-8DI-8RO

esphome:
  name: mainboard

esp32:
  board: esp32s3box
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "mainboard"
    password: !secret ap_password

captive_portal:


i2c:
  sda: GPIO42
  scl: GPIO41
  scan: true

# Use PCA9554 component (TCA9554 is compatible)
pca9554:
  - id: relay_expander
    address: 0x20

switch:
  - platform: gpio
    name: "Relay 1"
    pin:
      pca9554: relay_expander
      number: 0
      mode: output

  - platform: gpio
    name: "Relay 2"
    pin:
      pca9554: relay_expander
      number: 1
      mode: output

  - platform: gpio
    name: "Relay 3"
    pin:
      pca9554: relay_expander
      number: 2
      mode: output

  - platform: gpio
    name: "Relay 4"
    pin:
      pca9554: relay_expander
      number: 3
      mode: output

  - platform: gpio
    name: "Relay 5"
    pin:
      pca9554: relay_expander
      number: 4
      mode: output

  - platform: gpio
    name: "Relay 6"
    pin:
      pca9554: relay_expander
      number: 5
      mode: output

  - platform: gpio
    name: "Relay 7"
    pin:
      pca9554: relay_expander
      number: 6
      mode: output

  - platform: gpio
    name: "Relay 8"
    pin:
      pca9554: relay_expander
      number: 7
      mode: output
    
binary_sensor:
  - platform: gpio
    name: "DI1"
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    name: "DI2"
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    name: "DI3"
    pin:
      number: GPIO6
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    name: "DI4"
    pin:
      number: GPIO7
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    name: "DI5"
    pin:
      number: GPIO8
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    name: "DI6"
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    name: "DI7"
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    name: "DI8"
    pin:
      number: GPIO11
      mode: INPUT_PULLUP
      inverted: true