packages:
  common: !include
    file: templates/common.yaml
    vars:
      name: mainboard
  board: !include
    file: templates/waveshare-s3-eth-8di-8ro.yaml
  modbus2: !include
    file: templates/modbus.yaml
    vars:
      id: 2
      address: 2

  relay1: !include
    file: templates/relay.yaml
    vars:
      name: relay1
      pin: 0
  relay2: !include
    file: templates/relay.yaml
    vars:
      name: relay2
      pin: 1
  relay3: !include
    file: templates/relay.yaml
    vars:
      name: relay3
      pin: 2
  relay4: !include
    file: templates/relay.yaml
    vars:
      name: relay4
      pin: 3
  relay5: !include
    file: templates/relay.yaml
    vars:
      name: relay5
      pin: 4
  relay6: !include
    file: templates/relay.yaml
    vars:
      name: relay6
      pin: 5
  relay7: !include
    file: templates/relay.yaml
    vars:
      name: relay7
      pin: 6
  relay8: !include
    file: templates/relay.yaml
    vars:
      name: relay8
      pin: 7

  button1: !include
    file: templates/button.yaml
    vars:
      name: button1
      pin: GPIO4
      toggle: relay1
  button2: !include
    file: templates/button.yaml
    vars:
      name: button2
      pin: GPIO5
  button3: !include
    file: templates/button.yaml
    vars:
      name: button3
      pin: GPIO6
  button4: !include
    file: templates/button.yaml
    vars:
      name: button4
      pin: GPIO7
  button5: !include
    file: templates/button.yaml
    vars:
      name: button5
      pin: GPIO8
  button6: !include
    file: templates/button.yaml
    vars:
      name: button6
      pin: GPIO9
  button7: !include
    file: templates/button.yaml
    vars:
      name: button7
      pin: GPIO10
  button8: !include
    file: templates/button.yaml
    vars:
      name: button8
      pin: GPIO11
      toggle: relay11

  relay11: !include
    file: templates/modbus-relay.yaml
    vars:
      name: relay11
      address: 0
      slave: 2