substitutions:
  slave: 1
  address: 0

switch:
  - platform: modbus_controller
    modbus_controller_id: "modbus_controller${slave}"
    name: ${name}
    id: ${name}
    address: ${address}
    register_type: coil